---
all:
  children:

    linux:
      children:

        database:
          hosts:
            db01:
              ansible_host: 192.168.56.20

        monitoring:
          hosts:
            mon01:
              ansible_host: 192.168.56.30

        web:
          hosts:
            mon01:

        zabbix_api:
          hosts:
            mon01:

        agents:
          hosts:
            client01:
              ansible_host: 192.168.56.40

        production:
          hosts:
            db01:
            mon01:
            client01:

  vars:

    ansible_user: cadmin

    ansible_connection: ssh

    ansible_become: true

    ansible_become_method: sudo

    ansible_python_interpreter: /usr/bin/python3
